name: Main

on:
  push:
    branches:
      - master

jobs:
  buildHtmlFile:
    name: Build html file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build html file
        uses: yuta1031/github-actions/redoc-cli@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: bundle ./swagger.yaml
      - name: Upload to s3
        uses: actions/aws/cli@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          args: s3 cp ./redoc-static.html s3://redoc-test/ --acl public-read
