name: Master Push

on:
  push:
    branches:
      - master

jobs:
  buildHtmlFile:
    name: Build html file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build html file
        uses: yuta1031/github-actions/redoc-cli@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: bundle ./swagger.yaml -o index.html
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
