name: Pull Request

on: pull_request

jobs:
  buildHtmlFile:
    name: Build html file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build html file
        uses: yuta1031/github-actions/redoc-cli@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: bundle ./swagger.yaml
